apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-prod
  namespace: hello-prod
  labels:
    app: hello-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-prod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: hello-prod
    spec:
      containers:
        - name: hello-prod
          image: ghcr.io/mmurilo/terraform-aws-demo/hello-svc:hello-v0.1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: ENV
              value: "Production"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
