apiVersion: v1
kind: Service
metadata:
  name: hello-prod
  namespace: hello-prod
  labels:
    app: hello-prod
spec:
  selector:
    app: hello-prod
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
